### ISSUE TITLE
Component configuration for controller

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/federation-v2#114]
Follow-on to #101; this is to add (where it makes sense) additional configuration parameters beyond basic feature gating. For example: the push reconciler is enabled/disabled by feature gate, but the resync duration for the push reconciler would be configured by a distinct component configuration API field mapped to a CLI flag.

**Comment by xunpan** [comment]
I think it can be organized as a new `FederationConfig` API after read https://docs.google.com/document/d/1arP4T9Qkp2SovlJZ_y790sBeiWXDO6SG10pZ_UUU-Lc/edit and based on shashidharatd's proposal.
```
kind: FederationConfig 
apiVersion: v1 
metadata:
  namespace: federation-system
  name: federation-v2
data:
  install-crds: "false"
  limited-scope: "false"
  registry-namespace: kube-multicluster-public
  controller-duration:
    available-delay: "20s"
    unavailable-delay: "60s"
    user-monitor-period: "40s"
  leader-elect:
    enable: "true"
    lease-duration: "15s"
    renew-deadline: "10s"
    retry-period: "5s"
    resource-lock: configmaps
  feature-gates:
    push-reconciler: true
    scheduler-preferences: true
    cross-cluster-service-discovery: true
    federated-ingress: true
```
The behavior should be:
 - This resource should be created after federation namespace is created.
 - This resource only take effect in controller start up. Controller will not monitor it and reconcile variations of the resource (at least in current implementation)
 - This configuration will override command line options. Command line options is kept for current users.

The advantages from my point of view is the validation and better extendibility.

@marun @shashidharatd @pmorie

**Comment by marun** [comment]
@xunpan I have a couple of comments:

 - I don't think install-crds should be exposed.  It's more a vestige of our kubebuilder heritage than anything, and I think its use should be deprecated.
 - I'm not sure feature-gates should be a hard-coded list.  That would complicate a feature gaining sufficient maturity to be enabled without a feature gate, or a feature being deprecated and removed.  Is there any prior art in the document to refer to?  If not, consider using a list of objects with name/enabled properties, e.g.

```yaml
  feature-gates:
   - name: push-reconciler
     enabled: true
```

 - I think the command-line options should be deprecated (and perhaps removed before beta) in favor of accepting the yaml of the configuration type.  This strategy supports command-line users without imposing the burden of coordinating maintenance across the config type and the command line options.
