### ISSUE TITLE
Federation control plane should not use default service account

### ISSUE THREAD

**Issue by marun** [kubernetes-sigs/federation-v2#265]
As per a [comment](https://github.com/kubernetes-sigs/federation-v2/pull/230#discussion_r217504775) from @font, the federation control plane should use a dedicated service account rather than the default service account for the federation namespace.  Use of the default service account dates back to fedv1 when the  federation control plane api and the host cluster api were separate and federated workloads were unlikely to run in the federation namespace.

**Comment by pmorie** [comment]
I am majorly +1 on this. I would also add that the service account for federation should have a rolebinding to a least-privilege role based on the API operations the controller needs to function.

As part of that, we need to think about the RBAC story for the federation template,overrides,placement resources - perhaps this supports having a distinct API group for the 'federation API for kubernetes' portion of our API surface a la #256

**Comment by gyliu513** [comment]
I think there are two ClusterRoles need to handle:

1) Need to have permission to create the federation control plane. We are now using `cluster-admin` role, but seems using a ClusterRole should help.

```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    api: federation
    kubebuilder.k8s.io: 1.0.0
  name: federation-controller
rules:
- apiGroups:
  - ""
  - extensions
  - apps
  - batch
  resources:
  - '*'
  verbs:
  - '*'
```

2) Make sure the federation controller has permission to create resources in federation cluster, like creating federated resource etc. This was already handled now but we are binding the ClusterRole to default service account, seems we need to create a new serviceAccount for this but not default account.

```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    api: federation
    kubebuilder.k8s.io: 1.0.0
  name: federation-role
rules:
- apiGroups:
  - scheduling.federation.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - multiclusterdns.federation.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - core.federation.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
```

One question for @pmorie , does the `kubebuilder` support generating `ClusterRole` and `ClusterRoleBinding` for a specified serviceAccount?
