### ISSUE TITLE
Provide More Flexibility in Federated Service DNS Naming

### ISSUE THREAD

**Issue by danehans** [kubernetes-sigs/federation-v2#329]
I am using Federated Service DNS with [ExternalDNS](https://github.com/kubernetes-incubator/external-dns) to expose a `Service` from an Istio service mesh. The Istio `Gateway` resource is used to expose mesh applications outside the Kubernetes cluster. The `Gateway` resource is front-ended by a Kubernetes `Service`. More details can be found [here](https://istio.io/docs/examples/bookinfo/#determining-the-ingress-ip-and-port). 

`MultiClusterServiceDNSRecord` uses the `name` field to match the correct `Service` resource for creating an external DNS name and for the DNS A/TXT resource record prefix. For example:

__Service__:
```
apiVersion: v1
kind: Service
metadata:
<SNIP>
  labels:
    app: istio-ingressgateway
    chart: gateways-1.0.1
    heritage: Tiller
    istio: ingressgateway
    release: RELEASE-NAME
  name: istio-ingressgateway
  namespace: istio-system
<SNIP>
spec:
<SNIP>
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: $LB_IP
```

__MultiClusterServiceDNSRecord__:
```
apiVersion: multiclusterdns.federation.k8s.io/v1alpha1
kind: MultiClusterServiceDNSRecord
metadata:
  name: istio-ingressgateway 
  namespace: istio-system
spec:
  federationName: federation-system
  dnsSuffix: daneyon.com
  recordTTL: 300
```

__ExternalDNS Resource Records__:
```
NAME                                                                                      TYPE  TTL    DATA
daneyon.com.                                                                              NS    21600  ns-cloud-c1.googledomains.com.,ns-cloud-c2.googledomains.com.,ns-cloud-c3.googledomains.com.,ns-cloud-c4.googledomains.com.
daneyon.com.                                                                              SOA   21600  ns-cloud-c1.googledomains.com. cloud-dns-hostmaster.google.com. 1 21600 3600 259200 300
istio-ingressgateway.istio-system.federation-system.svc.daneyon.com.                      A     300    $LB_IP
istio-ingressgateway.istio-system.federation-system.svc.daneyon.com.                      TXT   300    "heritage=external-dns,external-dns/owner=my-identifier"
istio-ingressgateway.istio-system.federation-system.svc.us-west1.daneyon.com.             A     300    $LB_IP
istio-ingressgateway.istio-system.federation-system.svc.us-west1.daneyon.com.             TXT   300    "heritage=external-dns,external-dns/owner=my-identifier"
istio-ingressgateway.istio-system.federation-system.svc.us-west1-b.us-west1.daneyon.com.  A     300    $LB_IP
istio-ingressgateway.istio-system.federation-system.svc.us-west1-b.us-west1.daneyon.com.  TXT   300    "heritage=external-dns,external-dns/owner=my-identifier"
```

Instead of creating A/TXT records in the form of `istio-ingressgateway.istio-system.federation-system.svc.us-west1-b.us-west1.daneyon.com`, I would prefer these records represent the app I am trying to expose instead of the Istio Ingress Gateway. Can the `name` field in `MultiClusterServiceDNSRecord` either:

A. Only be used to match the `Service` and use annotations or labels to provide the DNS record prefix.
B. Only be used as the DNS record prefix and use annotations or labels to match the `Service`.

**Comment by shashidharatd** [comment]
@danehans, the naming scheme of the DNS record is designed to accommodate all services in all namespaces that are possible within federation and is designed to fallback to other zone, region if there are no service shards in current cluster.

However, i agree with your requirement as you expressed. So my suggestion would be that we include optional dnsPrefix field in `MultiClusterServiceDNSRecord` and when specified, the controller writes one more record like dnsPrefix.dnsSuffix for that federated service and include all service shards in all clusters as targets.

**Comment by quinton-hoole-2** [comment]
@danehans @shashidharatd Just to let you know that I've seen this issue but not yet had time to digest it and reply yet.  There are a lot of moving parts and constraints regarding federated DNS, for example:

1. I seem to recall a practical limit of 6 components to a DNS record in kubernetes, and 
2. resolution within a cluster, and between clusters needs to work correctly via CNAME records
3. there were some security considerations regarding hijacking of DNS records between tenants, by e.g. crafting special service names and/or federation names.

I think that the federation-v1 solution addressed 1 and 2 but not 3.  Current federation-v2 probably the same.  It's not clear which of the above @danehans adheres to. It seems at least 1 gets violated?  Perhaps give it some more thought in light of the above until I have more time to digest it all.

**Comment by danehans** [comment]
I like @shashidharatd's idea of using `dnsPrefix`. If `dnsPrefix` is not provided, then the prefix of the resource record is constructed using the value of `Name`. With that said, I would like to get feedback on the  idea of adding `FederatedServiceDNSRecord` so multiple `MultiClusterServiceDNSRecord`'s that simply differ by `dnsPrefix` can be managed as a single resource and use overrides to manage the differences.

**Comment by shashidharatd** [comment]
> I like @shashidharatd's idea of using dnsPrefix. If dnsPrefix is not provided, then the prefix of the resource record is constructed using the value of Name. With that said, I would like to get feedback on the idea of adding FederatedServiceDNSRecord so multiple MultiClusterServiceDNSRecord's that simply differ by dnsPrefix can be managed as a single resource and use overrides to manage the differences.

overrides is for variation of resource across multiple clusters. I am not clear about achieving what you are asking for.

**Comment by danehans** [comment]
@shashidharatd adding `dnsPrefix` to the API was a big help. However, I believe it's even more helpful if this prefix was used to create additional zone/region specific resource records. This will allow users to have a consistent prefix with Istio resources that control ingress/egress traffic. I propose using the `<dnsPrefix>.<namespace>.<federation>.<svc>.<avl-zone>.<region>.<federation-domain>` if `<dnsPrefix>` is specified in `ServiceDNSRecord` instead of `<svc>.<namespace>.<federation>.<svc>.<avl-zone>.<region>.<federation-domain>`. I believe this will help for any service that gets exposed through a service/ingress controller (i.e. NGINX). Thoughts?

**Comment by danehans** [comment]
@shashidharatd I'm not fully convinced this should be closed yet. I feel we can still provide a better UX. This is the ServiecDNSRecord that I must use for the federated istio use case:
```
apiVersion: multiclusterdns.federation.k8s.io/v1alpha1
kind: ServiceDNSRecord
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  domainRef: external
  dnsPrefix: bookinfo
  externalName: bookinfo
  recordTTL: 300
```

If `externalName` is specified, what are your thoughts about also creating a CNAME record like what  `dnsPrefix` provides?
