### ISSUE TITLE
Implement FederatedServiceOverride API type

### ISSUE THREAD

**Issue by danehans** [kubernetes-sigs/federation-v2#367]
I need the ability to change the service `type` depending on the environment of the cluster. For example, some clusters will use `NodePort` while others may use `LoadBalancer`.

**Comment by irfanurrehman** [comment]
I was actually on my way to bootstrap the service type and add needed override fields to it. At my end we need to override `annotations`. However, after looking at what @marun is trying to achieve in https://github.com/kubernetes-sigs/federation-v2/pull/340, that might not be needed. What I am assuming is `kubefed federate` should be able to generate needed types and CRD placeholders for the type to federate. The user should then further be able to add needed fields to the override CRD yamls (and paths in the relevant TypeConfig) to override  specific fields. @marun to confirm/correct, or probably explain this better then me.

**Comment by marun** [comment]
@irfanurrehman After reviewing #357, and seeing hard-coded override fields (e.g. [replicas for deployments](https://github.com/kubernetes-sigs/federation-v2/blob/master/pkg/apis/core/v1alpha1/federateddeploymentoverride_types.go#L33)) with fresh eyes, I think it's time for generic overrides.  I think a simple scheme could be as follows:

```yaml
apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedServiceOverride
metadata:
  name: foo
  namespace: bar
spec:
  overrides:
  - clusterName: cluster1
     clusterOverrides:
     - path: spec.type
        value: NodePort
  - clusterName: cluster2
     clusterOverrides:
     - path: spec.type
        value: LoadBalancer
```

Alternately we could go full-on json patch.  The complexity of that seems a bit daunting to me, and I wonder if overrides couldn't optionally allow either simple path-based replacement and patching:

```yaml
apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedServiceOverride
metadata:
  name: foo
  namespace: bar
spec:
  overrides:
  - clusterName: cluster1
     clusterOverrides:
     - path: spec.type
        value: NodePort
  - clusterName: cluster2
     clusterOverrides:
     # Equivalent json patch directive
     - json: { "op": "replace", "path": "/spec/type", "value": "LoadBalancer" }
```

I am concerned that mandating json patching as the only override mechanism will make for bad UX, but maybe overrides are more likely to be managed by controllers than users.
