### ISSUE TITLE
Generic overrides

### ISSUE THREAD

**Issue by marun** [kubernetes-sigs/federation-v2#400]
As per a [comment](https://github.com/kubernetes-sigs/federation-v2/issues/367#issuecomment-433912857) on #367, the recent implementation of `kubefed2 federate` has highlighted the need to support generic overrides (in which _almost_ [1] any field can be overridden).  Without generic overrides, generated override types could vary by deployment and this would complicate productization.

A simple path-based proposal:

```yaml
apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedServiceOverride
metadata:
  name: foo
  namespace: bar
spec:
  overrides:
  - clusterName: cluster1
     clusterOverrides:
     - path: spec.type
       value: NodePort
  - clusterName: cluster2
     clusterOverrides:
     - path: spec.type
       value: LoadBalancer
```

This simple approach does not preclude the future implementation of optional json-patch based overrides:

```yaml
apiVersion: generated.federation.k8s.io/v1alpha1
kind: FederatedServiceOverride
metadata:
  name: foo
  namespace: bar
spec:
  overrides:
  - clusterName: cluster1
     clusterOverrides:
     - path: spec.type
       value: NodePort
  - clusterName: cluster2
     clusterOverrides:
     # Equivalent json patch directive
     - json: { "op": "replace", "path": "/spec/type", "value": "NodePort" }
```

1: `name` and `namespace` will not be allowed to be overridden to ensure associativity is maintained between primitive resources and resources propagated to member clusters.
