### ISSUE TITLE
Federation of placement stops when clusterName duplicated in override

### ISSUE THREAD

**Issue by jewzaam** [kubernetes-sigs/federation-v2#588]
**What happened**:
Created a FedreatedConfigMap, FederatedConfigMapPlacement, and FederatedConfigMapOverride.  Initial override settings had unique `clusterName` values listed.  I updated it to include a duplicate `clusterName` and the change was not federated.  Subsequent updates to the config map are not federated either.  I was unable to find an error in the federation-controller-manager log.  None of the CRs have status to indicate anything either.

**What you expected to happen**:
At least have some error bubbled up so it's clear something failed.  Discussing in https://github.com/kubernetes-sigs/federation-v2/issues/581 that it might pick one of them instead of failing.  Not sure what is really desired.

**How to reproduce it (as minimally and precisely as possible)**:
I have 3 clusters, nmalik-test1, nmalik-test2.

Initial configMap setup:
```
---
apiVersion: v1
kind: Namespace
metadata:
    name: nmalik-config
---
apiVersion: primitives.federation.k8s.io/v1alpha1
kind: FederatedNamespacePlacement
metadata:
  name: nmalik-config
  namespace: nmalik-config
spec:
  clusterSelector: {}
---
apiVersion: primitives.federation.k8s.io/v1alpha1
kind: FederatedConfigMap
metadata:
  name: nmalik-cm
  namespace: nmalik-config
spec:
  template:
    data:
      A: ala ma kota
---
apiVersion: primitives.federation.k8s.io/v1alpha1
kind: FederatedConfigMapPlacement
metadata:
  name: nmalik-cm
  namespace: nmalik-config
spec:
  clusterSelector: {}
---
apiVersion: primitives.federation.k8s.io/v1alpha1
kind: FederatedConfigMapOverride
metadata:
  name: nmalik-cm
  namespace: nmalik-config
spec:
  overrides:
  - clusterName: openshift-hive-nmalik-test1
    clusterOverrides:
    - path: data
      value:
        A: OVERRIDEN
```

Values are federated as expected to target clusters.

Add duplicate `clusterName` and change the config map (which should be updated on nmalik-test2);
```
---
apiVersion: primitives.federation.k8s.io/v1alpha1
kind: FederatedConfigMapOverride
metadata:
  name: nmalik-cm
  namespace: nmalik-config
spec:
  overrides:
  - clusterName: openshift-hive-nmalik-test1
    clusterOverrides:
    - path: data
      value:
        A: OVERRIDEN
  - clusterName: openshift-hive-nmalik-test1
    clusterOverrides:
    - path: data
      value:
        A: OVERRIDEN a second time
---
apiVersion: primitives.federation.k8s.io/v1alpha1
kind: FederatedConfigMap
metadata:
  name: nmalik-cm
  namespace: nmalik-config
spec:
  template:
    data:
      A: ala ma kota UPDATED
```

The config map isn't updated because override has duplicated `clusterName`.

Remove the duplication and the updated config map lands on the cluster without the override.
```
---
apiVersion: primitives.federation.k8s.io/v1alpha1
kind: FederatedConfigMapOverride
metadata:
  name: nmalik-cm
  namespace: nmalik-config
spec:
  overrides:
  - clusterName: openshift-hive-nmalik-test1
    clusterOverrides:
    - path: data
      value:
        A: OVERRIDEN
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`)
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

- Federation version
v0.0.4

- Install method (helm vs script)
script

- Install configuration (namespaced vs cluster-scoped)
cluster-scoped

- Others

/kind bug
