### ISSUE TITLE
API driven federation of arbitrary types

### ISSUE THREAD

**Issue by pmorie** [kubernetes-sigs/federation-v2#60]
Related to #34; assuming that we have a CRD-based way to extend federation by creating some new CRD resources for:

- template
- override
- placement

...then there should be an API resource to have these CRDs created automatically. Example:

```yaml
kind: FederatedAPI
metadata:
  name: statefulset
spec:
  basis:
    group: apps
    version: v1
    kind: StatefulSet
  target:
    group: federation.k8s.io
    version: v1alpha1
```

A controller would list/watch this API resource and ensure that the correct CRDs were created for the named `basis` in the API group/version described by `target. In this example those would be:

- `FederatedStatefulSet` (possibly creating the OpenAPI schema and validations based on the OpenAPI for the basis type)
- `FederatedStatefulSetOverride`
- `FederatedStatefulSetPlacement`

In order to have automatic federation of all the registered types in an API server, there could also be a controller that examines the discovery endpoint for a cluster and ensures a `FederatedAPI` exists for the right API services. There are a number of ways a controller might be configured, like:

- configmap holding explicit configuration
- annotations on `APIService` and `CustomResourceDefinition` resources

idea formulated with @marun 

**Work Items**

- [x] Factor propagated version handling out of the sync controller (#273)
- [x] Factor type-specific version manager code into adapter (#276)
- [x] Add api generation to kubefed (??)
