### ISSUE TITLE
Deleting a FederatedNamespace does not delete the federated namespaces

### ISSUE THREAD

**Issue by andersjanmyr** [kubernetes-sigs/federation-v2#618]
**What happened**:
I have a federated namespace which is placed on 2 clusters.
```
# namespace.yaml
apiVersion: types.federation.k8s.io/v1alpha1
kind: FederatedNamespace
metadata:
  name: test-namespace
  namespace: test-namespace
spec:
  placement:
    clusterNames:
      - cluster1
      - cluster2
```

 When I delete the federated resource with `kubectl delete -f namespace.yaml`, the federated resources are not deleted. If I instead of deleting the `FederatedNamespace`, I update it by setting 
the clusterNames to an empty array, the clusters are deleted.
```
  placement:
    clusterNames: []
```

**What you expected to happen**:
I expected the federated resources to be deleted.

**How to reproduce it (as minimally and precisely as possible)**:
Apply the `namespace.yaml`, then delete it again. 

**Anything else we need to know?**:

**Environment**:
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-04T04:48:55Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T06:59:37Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
- Federation version (master build, or tag v0.0.6)
- Install method (helm)
- Install configuration (cluster-scoped)

/kind bug
