### ISSUE TITLE
Higher level placement specification aka label selector based placement

### ISSUE THREAD

**Issue by irfanurrehman** [kubernetes-sigs/federation-v2#87]
Per resource placement, where the corresponding placement resource specifies a list of clusters to place the template is already available. It also makes a lot of sense to have a default behavior for all resources in the abscence of this per object placement specification (as alluded in #75).
   There additionally is a need for a higher level placement intent that a user can specify. Although there could be more extensive placement policies that can be defined, this issue lists the need of a simple label selector based placement intent useful to the end user.

A simple spec for this resource (names could change) could be as below:
```
apiVersion: placement.federation.k8s.io/v1alpha1
kind: Preference
metadata:
  namespace: my-ns
  name: my-placement-preference
spec:
  # Select resources in the namespace whose labels match
  resourceSelector: app=myapp
  # Select labelled clusters
  clusterSelector: region=eu, zone=east
```
